-- Migration for Gallery, Documents, and Testimonials features

-- 0. Create Auth helper functions if they don't exist
--    These are used by RLS policies to get user data from the JWT.

CREATE OR REPLACE FUNCTION public.get_my_claim(claim TEXT)
RETURNS JSONB
LANGUAGE sql STABLE
AS $$
  SELECT COALESCE(
    current_setting('request.jwt.claims', true)::jsonb -> claim,
    'null'::jsonb
  );
$$;

CREATE OR REPLACE FUNCTION public.get_user_id()
RETURNS TEXT
LANGUAGE sql STABLE
AS $$
  SELECT nullif(current_setting('request.jwt.claims', true)::jsonb ->> 'sub', '')::text;
$$;


-- 1. Create `gallery` table
CREATE TABLE public.gallery (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  src text NOT NULL,
  caption text,
  category text,
  uploaded_by bigint REFERENCES public.users(id) ON DELETE SET NULL
);

COMMENT ON TABLE public.gallery IS 'Stores images for the public website gallery.';

-- 2. Create `documents` table
CREATE TABLE public.documents (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  title text NOT NULL,
  description text,
  type text,
  file text NOT NULL,
  uploaded_by bigint REFERENCES public.users(id) ON DELETE SET NULL
);

COMMENT ON TABLE public.documents IS 'Stores downloadable public documents like brochures and timetables.';

-- 3. Create `testimonials` table
CREATE TABLE public.testimonials (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  name text NOT NULL,
  course text,
  body text NOT NULL,
  photo text,
  approved boolean NOT NULL DEFAULT true,
  user_id bigint REFERENCES public.users(id) ON DELETE SET NULL
);

COMMENT ON TABLE public.testimonials IS 'Stores student testimonials for the public website.';


-- 4. RLS Policies for the new tables
--    These policies allow anyone to read the content, but only admins to modify it.

-- Gallery RLS
ALTER TABLE public.gallery ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public can view gallery images" ON public.gallery
  FOR SELECT USING (true);

CREATE POLICY "Admins can manage gallery" ON public.gallery
  FOR ALL USING (get_my_claim('role') = '"admin"' OR get_my_claim('role') = '"superadmin"');

-- Documents RLS
ALTER TABLE public.documents ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public can view documents" ON public.documents
  FOR SELECT USING (true);

CREATE POLICY "Admins can manage documents" ON public.documents
  FOR ALL USING (get_my_claim('role') = '"admin"' OR get_my_claim('role') = '"superadmin"');

-- Testimonials RLS
ALTER TABLE public.testimonials ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public can view approved testimonials" ON public.testimonials
  FOR SELECT USING (approved = true);

CREATE POLICY "Admins can manage testimonials" ON public.testimonials
  FOR ALL USING (get_my_claim('role') = '"admin"' OR get_my_claim('role') = '"superadmin"');